{
 "title": "Jobs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Jobs processing [5m]",
   "type": "timeseries",
   "description": "Jobs requests received (in) and results produced (out) per second [5m avg]",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(sum by(job) (rate(frontend_jobs_received_total[5m])), \"job\", \"$1 (in)\", \"job\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum by(job) (rate(frontend_jobs_completed_total[5m])), \"job\", \"$1 (out)\", \"job\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job processing time",
   "type": "timeseries",
   "description": "Time to process a single job",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by(job) (frontend_object_processing_time_seconds{quantile=\"0.99\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job wait queue",
   "type": "timeseries",
   "description": "Number of jobs waiting for child jobs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(job) (frontend_job_waiting_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Issues [5m]",
   "type": "timeseries",
   "description": "Number of rescheduled and timed-out jobs per second [5m avg]",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "label_replace(sum by(job) (rate(frontend_jobs_timed_out_total[5m])), \"job\", \"$1 timeout\", \"job\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum by(job) (rate(frontend_jobs_rescheduled_total[5m])), \"job\", \"$1 resched\", \"job\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}