{
 "title": "Work",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Work processing [5m]",
   "type": "timeseries",
   "description": "Work requests received and results generated per second (5m avg)",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(sum by(job) (rate(endpoint_work_requests_total[5m])), \"job\", \"requests\", \"job\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum by(job) (rate(grapher_works_total[5m])), \"job\", \"results\", \"job\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work time  [q=0.99]",
   "type": "timeseries",
   "description": "Time to process a work request",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "label_replace(avg(frontend_work_processing_time_seconds{quantile=\"0.99\"}), \"job\", \"processing\", \"__name__\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(avg by(job) (grapher_work_total_time_seconds{quantile=\"0.99\"}), \"job\", \"total\", \"job\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graphing latency [q=0.99]",
   "type": "timeseries",
   "description": "Time to convert a work result into a graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "avg by(job) (grapher_graphing_latency_seconds{quantile=\"0.99\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}